blank_issues_enabled: true
contact_links:
  - name: 💬 Discussion générale
    url: https://github.com/datanaos/detection_non_structure_file/discussions
    about: Pour les questions générales et discussions ouvertes
  - name: 📚 Documentation
    url: https://github.com/datanaos/detection_non_structure_file/wiki
    about: Consultez notre documentation
